name: Venkat docker deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building the docker image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: venkat-sample-docker
          IMAGE_TAG: ${{ github.sha }}

        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy to server

    runs-on: ubuntu-latest

    needs: build

    env:
      REGISTRY: 501804114434.dkr.ecr.us-east-2.amazonaws.com
      REPOSITORY: venkat-sample-docker
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Execute SSH Commands on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            whoami

            export REGISTRY=${{ env.REGISTRY }}
            export REPOSITORY=${{ env.REPOSITORY }}
            export IMAGE_TAG=${{ env.IMAGE_TAG }}

            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REGISTRY

            docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG

            docker run -itd -p 5050:5000 --name venkat-app $REGISTRY/$REPOSITORY:$IMAGE_TAG
